//
//  main.swift
//  ComputerLogicExercises
//
//  Created by Ronaldo Gomes on 21/11/20.
//

import Foundation

let functions = Functions()
let tableaux = Tableaux()

let formula1 = Atom("p")
let formula2 = Atom("q")
let formula0 = Not(formula2)
let formula3 = Or(formula1, formula2)
let formula4 = And(Atom("p"), Atom("s"))
let formula5 = Not(And(Atom("p"), Atom("s")))
let formula6 = Or(Not(And( Atom("p"), Atom("s"))), Atom("q"))
let formula7 = Implies(Not(And(Atom("p"), Atom("s"))), And(Atom("q"), Atom("r")))
let formula8 = Implies(Not(And(Atom("p"), Atom("s"))), And(Atom("q"), Not(And(Atom("p"), Atom("s")))))
let formula9 = Atom("r")
let formula11 = Atom("t")
let formula10 = Implies(formula3, formula9)
let formula12 = Or(formula9, formula11)
let formula13 = Implies(formula1, formula0)
let formula14 = Not(Implies(formula3, formula1))
let formula15 = Or(Or(And(formula1, formula2), Not(formula1)), formula0)
let formula16 = Implies(formula1, formula0)
let formula17 = Not(Implies(formula1, formula3))
let formula18 = And(And(Implies(formula1, formula2), Or(formula9, Not(formula2))),
                    And(Or(formula11, Not(formula9)), formula1))
let formula19 = And(And(And(Not(Atom("a")), Not(Atom("b"))), Not(Atom("c"))), Not(Atom("d")))


print("Formulas logicas")
print(formula0.getFormulaDescription())
print(formula1.getFormulaDescription())
print(formula2.getFormulaDescription())
print(formula3.getFormulaDescription())
print(formula4.getFormulaDescription())
print(formula5.getFormulaDescription())
print(formula6.getFormulaDescription())
print(formula7.getFormulaDescription())
print(formula8.getFormulaDescription())
print(formula9.getFormulaDescription())
print(formula10.getFormulaDescription())
print(formula11.getFormulaDescription())
print(formula12.getFormulaDescription())
print(formula13.getFormulaDescription())
print(formula14.getFormulaDescription())
print(formula15.getFormulaDescription())
print(formula16.getFormulaDescription())
print(formula17.getFormulaDescription())
print(formula18.getFormulaDescription())

print("Quantidade de atomos de cada formula")
print("\(formula0.getFormulaDescription()): \(functions.numberOfAtoms(formula: formula0))")
print("\(formula1.getFormulaDescription()): \(functions.numberOfAtoms(formula: formula1))")
print("\(formula3.getFormulaDescription()): \(functions.numberOfAtoms(formula: formula3))")
print("\(formula8.getFormulaDescription()): \(functions.numberOfAtoms(formula: formula8))")

print("Quantidade de connectivos de cada formula")
print("\(formula0.getFormulaDescription()): \(functions.connec(formula: formula0))")
print("\(formula1.getFormulaDescription()): \(functions.connec(formula: formula1))")
print("\(formula3.getFormulaDescription()): \(functions.connec(formula: formula3))")
print("\(formula5.getFormulaDescription()): \(functions.connec(formula: formula5))")
print("\(formula7.getFormulaDescription()): \(functions.connec(formula: formula7))")
print("\(formula8.getFormulaDescription()): \(functions.connec(formula: formula8))")

print("Atomos de cada formula")
print("\(formula1.getFormulaDescription()): \(functions.listOfAtoms(formula: formula1))")
print("\(formula3.getFormulaDescription()): \(functions.listOfAtoms(formula: formula3))")
print("\(formula8.getFormulaDescription()): \(functions.listOfAtoms(formula: formula8))")

print("Substituicao")
print("\(functions.substitution(formula: formula10, oldSubformula: formula0, newSubformula: formula12).getFormulaDescription())")

print("Valor verdade de cada formula")
print("\(formula0.getFormulaDescription()): \(functions.truthValue(formula: formula0, interpretation: ["q": true]))")
print("\(formula0.getFormulaDescription()): \(functions.truthValue(formula: formula0, interpretation: ["q": false]))")
print("\(formula1.getFormulaDescription()): \(functions.truthValue(formula: formula1, interpretation: ["p": false]))")
print("\(formula12.getFormulaDescription()): \(functions.truthValue(formula: formula12, interpretation: ["r": false, "t": true]))")
print("\(formula12.getFormulaDescription()): \(functions.truthValue(formula: formula12, interpretation: ["r": false, "t": false]))")
print("\(formula3.getFormulaDescription()): \(functions.truthValue(formula: formula3, interpretation: ["p": true, "q": false]))")
print("\(formula3.getFormulaDescription()): \(functions.truthValue(formula: formula3, interpretation: ["p": true, "q": true]))")
print("\(formula8.getFormulaDescription()): \(functions.truthValue(formula: formula8, interpretation: ["p": false, "s": false, "q": true]))")
print("\(formula8.getFormulaDescription()): \(functions.truthValue(formula: formula8, interpretation: ["p": false, "s": false, "q": false]))")
print("\(formula8.getFormulaDescription()): \(functions.truthValue(formula: formula8, interpretation: ["p": true, "s": true, "q": false]))")
print("\(formula8.getFormulaDescription()): \(functions.truthValue(formula: formula8, interpretation: ["p": true, "s": true, "q": false]))")
print("\(formula19.getFormulaDescription()): \(functions.truthValue(formula: formula19, interpretation: ["d": false]))")

print("Satisfabilidade de cada formula")
print("\(formula3.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula3))")
print("\(formula13.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula13))")
print("\(formula10.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula10))")
print("\(formula8.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula8))")
print("\(formula15.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula15))")
print("\(formula14.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula14))")
print("\(formula17.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula17))")
print("\(formula18.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula18))")
print("\(formula19.getFormulaDescription()): \(functions.satisfabilityChecking(formula: formula19)))")

print("Validade de cada formula")
print("\(formula3.getFormulaDescription()): \(functions.validityChecking(formula: formula3))")
print("\(formula13.getFormulaDescription()): \(functions.validityChecking(formula: formula13))")
print("\(formula7.getFormulaDescription()): \(functions.validityChecking(formula: formula7))")
print("\(formula10.getFormulaDescription()): \(functions.validityChecking(formula: formula10))")
print("\(formula8.getFormulaDescription()): \(functions.validityChecking(formula: formula8))")
print("\(formula15.getFormulaDescription()): \(functions.validityChecking(formula: formula15))")
print("\(formula14.getFormulaDescription()): \(functions.validityChecking(formula: formula14))")
print("\(formula17.getFormulaDescription()): \(functions.validityChecking(formula: formula17))")

print("Consequencia logica")
print("\(formula3.getFormulaDescription()), \(formula5.getFormulaDescription()) |= \(formula0.getFormulaDescription()) : \(functions.logicalConsequence(premise: [formula3, formula5], conclusion: formula0))")
print("\(formula0.getFormulaDescription()), \(formula10.getFormulaDescription()) |= \(formula8.getFormulaDescription()) : \(functions.logicalConsequence(premise: [formula0, formula10], conclusion: formula8))")
print("\(formula1.getFormulaDescription()) |= \(formula2.getFormulaDescription()) : \(functions.logicalConsequence(premise: [formula0, formula1], conclusion: formula2))")

print("Contradição")
print("\(formula0.getFormulaDescription()) + \(formula2.getFormulaDescription()) contra \(tableaux.isContradiction(results: [formula0, formula2]))")
print("\(formula2.getFormulaDescription()) + \(formula0.getFormulaDescription()) contra \(tableaux.isContradiction(results: [formula0, formula2]))")
print("\(formula0.getFormulaDescription()) + \(formula1.getFormulaDescription()) contra \(tableaux.isContradiction(results: [formula0, formula1]))")

print("Tableaux de cada formula")
print("\(formula3.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula3], isCheck: [false]))")
print("\(formula13.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula13], isCheck: [false]))")
print("\(formula10.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula10], isCheck: [false]))")
print("\(formula8.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula8], isCheck: [false]))")
print("\(formula15.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula15], isCheck: [false]))")
print("\(formula14.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula14], isCheck: [false]))")
print("\(formula17.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula17], isCheck: [false]))")
print("\(formula18.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula18], isCheck: [false]))")
print("\(formula19.getFormulaDescription()): \(tableaux.tableaux(formulas: [formula19], isCheck: [false])))")

